FROM node:18-alpine

WORKDIR /app

# Copy dependency files first for caching
COPY backend/package*.json ./

RUN npm install

# Copy backend source files
COPY backend/ ./

# Build TypeScript to Javascript
RUN npm run build

EXPOSE 5000

ENV PORT=5000

CMD ["npm", "start"]
